### ISSUE TITLE
Allow no-command (signed-off-by) steps

### ISSUE THREAD

**Issue by lukpueh** [in-toto/layout-web-tool#10]
@JustinCappos suggested that there might be steps that are not related to a command or any file modifications, e.g. for code reviews.

We should add  "no command" options (probably only to the `qa` page) to accommodate such needs.  Also we probably need to add a `no-command` flag to `in-toto-run`.

**Comment by ShikherVerma** [comment]
I could take up this one. @lukpueh ?

**Comment by lukpueh** [comment]
Sure, go ahead.
